/*
 * Generates INCLUDE/SWEEP.H
 * OPL register values for the DOS MDFourier sequence.
 * Build and run on a modern machine (C99/mingw64):
 *     gcc -O2 -o gensweep TOOLS/GENSWEEP.C -lm
 *     ./gensweep > INCLUDE/SWEEP.H
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define STEPS    128        /* sweep notes */
#define MIN_HZ   20.0       /* first note */
#define MAX_HZ   6200.0     /* last note, OPL tops out at 6209 Hz */
#define REF_HZ   6000.0     /* sync pulses and chip ID tone */
#define BASE_HZ  49716      /* OPL2/OPL3 sample rate: 3.579545 MHz / 72 */
#define CLK_ELEM 2          /* CHIPID index in the MDF profile */

/* rounding boundary */
#define MARGIN   1e-6

/* Lowest Block that fits in 10 bits */
int block_fnum(double freq, int *block, int *fnum) {
    int b;

    for (b = 0; b < 8; b++) {
        double exact;
        int    fn;

        exact = freq * pow(2.0, 20 - b) / BASE_HZ;
        fn = (int)floor(exact + 0.5);

        if (fn <= 1023) {
            if (fabs(exact - floor(exact) - 0.5) < MARGIN) {
                fprintf(stderr, "too close to ounding boundary: %.17g Hz\n", freq);
                return 0;
            }
            if (fabs(exact - 1023.5) < MARGIN) {
                fprintf(stderr, "too close to Block boundary: %.17g Hz\n", freq);
                return 0;
            }
            *block = b;
            *fnum = fn;
            return 1;
        }
    }
    fprintf(stderr, "frequency out of OPL range: %.17g Hz\n", freq);
    return 0;
}

double played(int block, int fnum) {
    return fnum * (double)BASE_HZ/pow(2.0, 20-block);
}

int main() {
    int    block[STEPS], fnum[STEPS], i, rblock, rfnum;
    double freq[STEPS], play[STEPS], worst = 0.0, rate_played, ratio;

    for (i = 0; i < STEPS; i++) {
        double cents;

        freq[i] = MIN_HZ * pow(MAX_HZ/MIN_HZ, (double)i/(STEPS-1));
        if(!block_fnum(freq[i], &block[i], &fnum[i]))
            return 0;
        play[i] = played(block[i], fnum[i]);
        cents = fabs(1200.0*log2(play[i]/freq[i]));
        if (cents > worst)
            worst = cents;
    }

    if(!block_fnum(REF_HZ, &rblock, &rfnum))
        return 0;
    rate_played = played(rblock, rfnum);
    ratio = pow(2.0, 20-rblock)/rfnum;

    printf("/*\n");
    printf(" * Generated by TOOLS/GENSWEEP.C *do not edit* regenerate\n");
    printf(" *\n");
    printf(" * Register values fixed and not computed to guarantee stability\n");
    printf(" *\n");
    printf(" * Sweep: f = %g * (%g/%g)^(i/%d), i = 0..%d\n", MIN_HZ, MAX_HZ, MIN_HZ, STEPS - 1, STEPS - 1);
    printf(" *        Fnum = round(f * 2^(20-Block) / %d), lowest Block\n", BASE_HZ);
    printf(" *        with Fnum <= 1023. Played within %.1f cents of f.\n", ceil(worst * 10.0) / 10.0);
    printf(" *\n");
    printf(" * Reference tone: %g Hz requested, %.4f Hz played.\n", REF_HZ, rate_played);
    printf(" * Profile clock line:\n");
    printf(" *   CLK y %d %.4f %.4f\n", CLK_ELEM, rate_played, ratio);
    printf(" */\n\n");
    printf("#ifndef SWEEP_H\n#define SWEEP_H\n\n");
    printf("#include <stdint.h>\n\n");
    printf("#define SWEEP_MIN_HZ %du\n", (int)MIN_HZ);
    printf("#define SWEEP_MAX_HZ %du\n\n", (int)MAX_HZ);
    printf("/* Sync pulses and chip ID tone */\n");
    printf("#define REF_BLOCK    %d\n", rblock);
    printf("#define REF_FNUM     %d\n\n", rfnum);
    printf("static const struct {\n");
    printf("    uint8_t  block;\n");
    printf("    uint16_t fnum;\n");
    printf("} sweep[] = {\n");
    for (i = 0; i < STEPS; i++)
        printf("    { %d, %4d }%s  /* %3d: %8.2f Hz -> %8.2f Hz */\n",
               block[i], fnum[i], i < STEPS - 1 ? "," : " ", i, freq[i], play[i]);
    printf("};\n\n");
    printf("#define SWEEP_STEPS  (sizeof(sweep) / sizeof(sweep[0]))\n\n");
    printf("#endif\n");

    return 0;
}
